### ISSUE TITLE
EAI_AGAIN error when trying to make a request

### ISSUE THREAD

**Issue by varwiz** [kbarresi/calais-entity-extractor#1]
does this module  still conform to opencalais api standards? I get the following error,

"Uh oh, we got an error! : Error: getaddrinfo EAI_AGAIN"

Im behind a proxy but I have it configured in npm config(both http and https)

**Comment by kbarresi** [comment]
Yes I can confirm it still works. Do you have the same error when not running it behind a proxy? The manpage for `getaddrinfo` says:

```
EAI_AGAIN
The name server returned a temporary failure indication. Try again later.
```

**Comment by kbarresi** [comment]
Haven't heard a response, and I think this issue is specific to the given user's setup.
